### ISSUE TITLE
Support for certificate renewal?

### ISSUE THREAD

**Issue by joaomapi** [creactiviti/spring-boot-starter-acme#1]
Is there any?
Cheers

**Comment by runabol** [comment]
I haven't tested it yet but per the [acme4j docs](https://shredzone.org/maven/acme4j/usage/certificate.html)  you should be able to just re-run the command to generate a new, updated cert.

**Comment by sebasira** [comment]
Any update on this?

About re-running the command, you mean to restart the SpringBoot app?

**Comment by nxthor** [comment]
Hi! afaik you rerun the certbot command that generated your initial set of certificates with the option -renew or alike.  the certbot-project has recommendations for setting up a cron job.
